pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/jose-llancamil/AutoFix-System.git']])
                dir("autofix_frontend"){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("autofix_frontend"){
                    script{
                         withDockerRegistry(credentialsId: 'docker-credentials'){
                            bat "docker build -t josellancamil/frontend-image ."
                            bat "docker push josellancamil/frontend-image"
                        }
                    }                    
                }
            }
        }
    }
}
